"""Goal-group messages.

Groups deliberately have no membership table: a child is in a group exactly
while they hold a confirmed, matchable goal in that category and are
discoverable, so joining and leaving are the acts they already perform. Only
what was SAID needs storing, and it is stored the way peer_messages are —
before delivery, blocked rows included, because the row is the safety record.

Revision ID: 0034_group_messages
Revises: 0033_note_title_ci_unique
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0034_group_messages"
down_revision: str | None = "0033_note_title_ci_unique"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    op.create_table(
        "group_messages",
        sa.Column(
            "id",
            sa.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        # "<category>:<age_segment>" — segments never share a room.
        sa.Column("group_key", sa.String(64), nullable=False),
        sa.Column(
            "sender_child_id",
            sa.UUID(as_uuid=True),
            sa.ForeignKey("child_profiles.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("sender_name", sa.String(40), nullable=False),
        # GENERATED BY DEFAULT so the ORM can leave it out and read it back —
        # see the note on PeerMessage.seq.
        sa.Column(
            "seq",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            unique=True,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "moderation_state",
            # The existing type is peer_moderation_state; a mismatched name here
            # silently creates a second enum and every insert fails on it.
            postgresql.ENUM(name="peer_moderation_state", create_type=False),
            nullable=False,
            server_default="delivered",
        ),
        sa.Column("moderation_reason", sa.String(80), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.String(255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index("ix_group_messages_group_key", "group_messages", ["group_key"])
    op.create_index(
        "ix_group_messages_sender_child_id", "group_messages", ["sender_child_id"]
    )
    # The read path is always "this room, newest N", so the cursor index is
    # the composite one.
    op.create_index("ix_group_messages_key_seq", "group_messages", ["group_key", "seq"])


def downgrade() -> None:
    op.drop_index("ix_group_messages_key_seq", table_name="group_messages")
    op.drop_index("ix_group_messages_sender_child_id", table_name="group_messages")
    op.drop_index("ix_group_messages_group_key", table_name="group_messages")
    op.drop_table("group_messages")
