/**
 * GENERATED by the capture pipeline (capture/finish.py) — do not edit by
 * hand: recapture instead, and every number below is measured again.
 *
 * The DUYO app's screens as captured (see manifest.json for what each shows),
 * and what the site's phone needs to animate between them. Boxes are
 * [x, y, w, h] and positions y, in capture px: a capture is the phone face
 * below the status bar, 720 × 1492 (360 × 746 dp at 2×), gesture area
 * included.
 */
import chat_1 from './chat-1.webp?inline';
import chat_2 from './chat-2.webp';
import chat_3 from './chat-3.webp';
import chat_4 from './chat-4.webp';
import safety_1 from './safety-1.webp';
import safety_2 from './safety-2.webp';
import map_1 from './map-1.webp';
import map_2 from './map-2.webp';
import goals_1 from './goals-1.webp';
import goals_2 from './goals-2.webp';
import goals_3 from './goals-3.webp';
import goals_4 from './goals-4.webp';
import home_1 from './home-1.webp';

/** Android's status bar, 24 dp: the inset the captures were laid out under and cropped by. */
export const STATUS_BAR_PX = 48;
/** Android's gesture area, 16 dp: in the captures (the app's ground runs under it), handle not drawn. */
export const NAV_BAR_PX = 32;

export const SHOTS = {
  'chat-1': { src: chat_1, clock: '16:40', top: '#e3efff', bottom: '#f7f9fd' },
  'chat-2': { src: chat_2, clock: '16:40', top: '#e3efff', bottom: '#f7f9fd' },
  'chat-3': { src: chat_3, clock: '16:40', top: '#e3efff', bottom: '#f7f9fd' },
  'chat-4': { src: chat_4, clock: '16:40', top: '#e3efff', bottom: '#f7f9fd' },
  'safety-1': { src: safety_1, clock: '16:52', top: '#e3efff', bottom: '#eaf0fc' },
  'safety-2': { src: safety_2, clock: '16:52', top: '#e3efff', bottom: '#eaf0fc' },
  'map-1': { src: map_1, clock: '16:54', top: '#21093f', bottom: '#111b40' },
  'map-2': { src: map_2, clock: '16:54', top: '#21093f', bottom: '#111b40' },
  'goals-1': { src: goals_1, clock: '16:56', top: '#21093f', bottom: '#111b40' },
  'goals-2': { src: goals_2, clock: '16:56', top: '#e3efff', bottom: '#eff3fc' },
  'goals-3': { src: goals_3, clock: '16:56', top: '#e3efff', bottom: '#eff3fc' },
  'goals-4': { src: goals_4, clock: '16:56', top: '#e3efff', bottom: '#eff3fc' },
  'home-1': { src: home_1, clock: '16:58', top: '#d7e6fa', bottom: '#dee5f6' },
} as const;

export type ShotName = keyof typeof SHOTS;

export const GEOMETRY = {
  chat: {
    band: [128, 1290],
    anchor: {
      'chat-2': 986,
      'chat-3': 148,
      'chat-4': -20,
    },
    blank: 646,
    chalk: '#f2efe4',
    lines: [
      {
        kind: 'line',
        box: [84, 694, 352, 64],
        size: 22,
        chars: 16,
      },
      {
        kind: 'line',
        box: [84, 773, 318, 52],
        size: 18,
        chars: 19,
      },
      {
        kind: 'note',
        box: [84, 828, 552, 26],
        size: 0,
        chars: 29,
      },
      {
        kind: 'line',
        box: [84, 866, 476, 52],
        size: 18,
        chars: 26,
      },
      {
        kind: 'note',
        box: [84, 920, 552, 26],
        size: 0,
        chars: 24,
      },
      {
        kind: 'line',
        box: [84, 958, 366, 52],
        size: 18,
        chars: 22,
      },
      {
        kind: 'line',
        box: [84, 1022, 404, 52],
        size: 18,
        chars: 24,
      },
      {
        kind: 'answer',
        box: [84, 1118, 368, 64],
        size: 22,
        chars: 18,
      },
    ],
    answerBox: [84, 1098, 368, 84],
  },
  safety: {
    band: [310, 1346],
    anchor: {
      'safety-1': 999,
      'safety-2': 832,
    },
    draft: {
      box: [130, 1380, 364, 38],
      stops: [149, 164, 182, 199, 226, 233, 259, 268, 295, 314, 342, 361, 380, 407, 426, 453, 472],
      blank: 492,
    },
  },
  goals: {
    entry: {
      box: [102, 905, 216, 82],
      stops: [115, 127],
      blank: 316,
    },
    save: [366, 902, 172, 88],
    track: [74, 805, 572, 20],
    fill: {
      'goals-3': 382,
      'goals-4': 419,
    },
  },
} as const;
