"""peer_messages.seq must be generated by the database, not sent as NULL.

Every peer message 500'd on a NOT NULL violation because the column was
declared `autoincrement=True`, which is a no-op for SQLAlchemy's INSERT
builder on a non-primary-key column — the ORM sent an explicit NULL while the
table expected the identity default to fill it. Nothing caught this until the
feature was exercised end to end.
"""

from duyo.models.social import PeerMessage


def _seq_column():
    return PeerMessage.__table__.c.seq


def test_seq_is_server_generated():
    column = _seq_column()
    assert column.identity is not None, (
        "seq must carry Identity() so the ORM omits it from the INSERT; "
        "autoincrement=True does nothing on a non-primary-key column"
    )
    # BY DEFAULT, not ALWAYS — a backfill or restore has to be able to set it.
    assert column.identity.always is False


def test_seq_is_not_nullable_and_unique():
    """The ordering guarantee the client's cursor paging depends on."""
    column = _seq_column()
    assert column.nullable is False
    assert column.unique is True


def test_seq_carries_no_python_side_default():
    """Nothing may fill seq in Python — the database owns the sequence.

    A Python-side default would hand out numbers per process and collide the
    moment the API runs more than one worker, which it does.
    (`server_default` is not checked: SQLAlchemy stores Identity() there.)
    """
    assert _seq_column().default is None
